@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZDc2OWNjMjYxN2Q4NmQyOTg4YWM5MCIsImVtYWlsIjoiamFuZWRvZUBlbWFpbC5jb20iLCJ1c2VybmFtZSI6IkphbmVEb2UiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1ODk0OTE5MCwiZXhwIjoxNzU4OTUyNzkwfQ.7a2nStmGcHh3SafEfSYfb-LcVhNDaq5Rl0MSWMNGoYc


### Sign up
POST http://localhost:3000/api/v1/auth/sign-up
Content-Type: application/json

{
  "email": "janedoe@email.com",
  "username": "JaneDoe",
  "password": "passcode",
  "firstname": "Jane",
  "lastname": "Doe",
  "middlename": "Anna",
  "dateOfBirth": "2025-09-27T04:24:08.577Z",
  "signInType": "default"
}
### Sign in
POST http://localhost:3000/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "janedoe@email.com",
  "password": "passcode"
}

### me
GET http://localhost:3000/api/v1/users/user/me
Content-Type: application/json
Authorization: Bearer {{token}}


### Get all customers
GET http://localhost:3001/api/v1/customers
Accept: application/json

### Get all products
GET http://localhost:3002/api/v1/products
Accept: application/json

### Place an order
POST http://localhost:3003/api/v1/orders
Content-Type: application/json

{
  "customerId": "68d3b93a4990abbfdf56aa3c",
  "productId": "68d3b9a82e1f1d4988cc6771",
  "amount": 10
}

### Get transactions (saved by worker)
GET http://localhost:3004/api/v1/transactions
Accept: application/
