### Get all customers
GET http://localhost:3001/api/v1/customers
Accept: application/json

### Get all products
GET http://localhost:3002/api/v1/products
Accept: application/json

### Place an order
POST http://localhost:3003/api/v1/orders
Content-Type: application/json

{
  "customerId": "68d30a7024f63e7f755add6d",
  "productId": "68d30b7a28812791822b840e",
  "amount": 1500
}

### Get transactions (saved by worker)
GET http://localhost:3004/api/v1/transactions
Accept: application/json
